### ISSUE TITLE
Create translation mappings   🆕 

### ISSUE THREAD

**Issue by Nolski** [OpenMined/threepio#22]
# Summary

We want to create a comprehensive, automatic mapping between all of the commands in pytorch, tensorflow, and tensorflow.js.

# Details

These mappings should be stored in a number of json files to map functions to each other. Beyond that we should also map between args & kwargs as well as include support between a variety of versions for each library.

# Outcome

We should have a script that outputs several json files to be consumed by our threepio clients which will do a simple lookup and parsing of commands to run them in the desired framework.

# Sub-level projects

- [x] Create function name mapping file #20
- [x] Create argument mapping function files #21
- [ ] Support mapping between versions #3 
- [ ] Output statistics between command support based on mapping. #33
