### ISSUE TITLE
Create initial automatic translation layer in python 🆕 

### ISSUE THREAD

**Issue by Nolski** [OpenMined/threepio#23]
# Summary

We should support translating commands created in javascript to supported python libraries

# Background

**Describe the ideal solution**:

Create an endpoint that, given an input of a tensorflow.js command, will execute a corresponding command in Tensorflow or PyTorch

For the sake of this issue, this should only happen with commands that can directly map using the generated json files from the crawler.

# Outcome

This will allow rudimentary command translation between libraries to be used in PySyft

# Sub-level projects

- [x] Add initial basic conversion
- [x] Add initial test coverage
- [x] Build in support and tests with complex argument transformations & warnings.
- [x] Build in support for comprehensive Tensorflow.js library translations
- [x] Build & publish threepio python package
