### ISSUE TITLE
Create initial automatic translation layer in javascript 💭 

### ISSUE THREAD

**Issue by Nolski** [OpenMined/threepio#5]
# Summary

We should build automatic mappings between commands using our flat json files.

# Background

**Describe the ideal solution**:

Create an endpoint that, given an input of a PyTorch or Tensorflow command, will execute a corresponding command in Tensorflow.js.

For the sake of this issue, this should only happen with commands that can directly map using the generated json files from the crawler.

**Describe alternatives considered**:

This is an extension (and replacement) of the [torchToTF](https://github.com/OpenMined/syft.js/blob/master/src/_helpers.js#L27) function in syft.js

# Outcome

This will allow rudimentary command translation between libraries.

# Sub-level projects

- [x] Add initial test coverage (https://github.com/OpenMined/threepio/pull/15)
- [x] Build in support for comprehensive PyTorch MNIST translations #30 
- [x] Build in support for comprehensive Tensorflow library translations
- [x] Build & publish threepio.js javascript package

**Comment by cereallarceny** [comment]
@Nolski Can we close this?
